export const backgroundColors = {
  normal: "#F5F5DC",
  fire: "#FFF3E0",
  water: "#E3F2FD",
  electric: "#FFFDE7",
  grass: "#E8F5E9",
  ice: "#E0F7FA",
  fighting: "#FBE9E7",
  poison: "#F3E5F5",
  ground: "#FFF8E1",
  flying: "#EDE7F6",
  psychic: "#FCE4EC",
  bug: "#F1F8E9",
  rock: "#EFEBE9",
  ghost: "#E8EAF6",
  dragon: "#EDE7F6",
  dark: "#EFEBE9",
  steel: "#ECEFF1",
  fairy: "#FCE4EC",
};